# Generated by Django 4.0.6 on 2022-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(default=0)),
                ('M1B1', models.PositiveSmallIntegerField(default=0)),
                ('M1B2', models.PositiveSmallIntegerField(default=0)),
                ('M1B3', models.PositiveSmallIntegerField(default=0)),
                ('M2B1', models.PositiveSmallIntegerField(default=0)),
                ('M2B2', models.PositiveSmallIntegerField(default=0)),
                ('M2B3', models.PositiveSmallIntegerField(default=0)),
                ('M3B1', models.PositiveSmallIntegerField(default=0)),
                ('M3B2', models.PositiveSmallIntegerField(default=0)),
                ('M3B3', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
