# Generated by Django 4.0.6 on 2022-08-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FailuresList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.categorylist')),
            ],
            options={
                'verbose_name': 'Failure',
                'verbose_name_plural': 'Failures',
            },
        ),
        migrations.CreateModel(
            name='RunRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=0)),
                ('failure_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dash.failureslist')),
            ],
        ),
    ]
