# Generated by Django 4.0.6 on 2022-08-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorylist',
            old_name='Name',
            new_name='name',
        ),
    ]
