# Generated by Django 4.0.6 on 2022-07-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raspberryinfo',
            options={'verbose_name': 'Raspberry Info', 'verbose_name_plural': 'Raspberries Info'},
        ),
    ]
