# Generated by Django 4.0.6 on 2022-08-17 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_rename_name_categorylist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runregister',
            name='bottle_count',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='runregister',
            name='bottle_rejections',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runregister',
            name='duration',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='runregister',
            name='line_speed',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='runregister',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 15, 1, 57, 855132, tzinfo=utc)),
        ),
    ]
