# Generated by Django 4.0.6 on 2022-08-17 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_alter_runregister_bottle_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runregister',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 15, 6, 48, 936525, tzinfo=utc)),
        ),
    ]
