# Generated by Django 4.0.6 on 2022-08-17 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_alter_runregister_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runregister',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
